platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'DailyPlayground' do
  # Pods for DailyPlayground
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  # As part of `npm run install-dev`, the below are automatically replaced to
  # enable editing react-native-daily-js's and react-native-webrtc's native iOS
  # files directly in DailyPlayground without having to reinstall npm packages
  # and run another pod install
  # pod 'react-native-daily-js', :path => INSERT_PATH_HERE
  # pod 'react-native-webrtc', :path => INSERT_PATH_HERE

  target 'DailyPlaygroundTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end
end

target 'DailyPlayground-tvOS' do
  # Pods for DailyPlayground-tvOS

  target 'DailyPlayground-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
