require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'DailyPlayground' do
  # As part of `npm run install-dev`, the below are automatically replaced to
  # enable editing react-native-daily-js's and react-native-webrtc's native iOS
  # files directly in DailyPlayground without having to reinstall npm packages
  # and run another pod install
  # pod 'react-native-daily-js', :path => INSERT_PATH_HERE
  # pod 'react-native-webrtc', :path => INSERT_PATH_HERE

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'DailyPlaygroundTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
