# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'DailyPlayground' do
  # As part of `npm run install-dev`, the below are automatically replaced to
  # enable editing react-native-daily-js's and react-native-webrtc's native iOS
  # files directly in DailyPlayground without having to reinstall npm packages
  # and run another pod install
  # pod 'react-native-daily-js', :path => INSERT_PATH_HERE
  # pod 'react-native-webrtc', :path => INSERT_PATH_HERE
  # pod 'ReactNativeDailyJSScreenShareExtension', :podspec => INSERT_PATH_HERE

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'DailyPlaygroundTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
